### ISSUE TITLE
3D Model

### ISSUE THREAD

**Issue by vardelean** [solderparty/flexypin#5]
Hello, I purchased some flexypins and I'm trying to get the PCB design done, but for whatever reasons, I can't get the flexypin.step model to show up. 
I tried to open it with different viewers (Fusion360, Freecad and eDrawings), but the file won't open. Any advice?

Thank you!

**Comment by arturo182** [comment]
I just downloaded the file and had no problems opening it in Fusion 360. Maybe try to download the repo/file again, perhaps it somehow didn't download properly?

![image](https://github.com/solderparty/flexypin/assets/249082/e236a510-9446-488a-a869-00a1a95a9e12)

**Comment by vardelean** [comment]
Thank you kindly for the fast response!
I downloaded the file again and it works now. Not sure what went wrong when I first downloaded it. All good!

**Comment by arturo182** [comment]
Great to hear! :)
