### ISSUE TITLE
on aliexpress

### ISSUE THREAD

**Issue by eadmaster** [solderparty/flexypin#7]
are these the same?
https://www.aliexpress.com/item/1005006888371835.html

**Comment by arturo182** [comment]
They look similar but are not the same:

![image](https://github.com/solderparty/flexypin/assets/249082/96fabc1a-2693-4938-b290-f35b03e68362)
![image](https://github.com/solderparty/flexypin/assets/249082/49dfaede-e1f0-460a-8447-f789cb10b71b)

**Comment by eadmaster** [comment]
btw if i understand correctly they both need to be soldered on one leg to be used correctly, right?

Do you know if there's any alternative that does not require soldering at all? (Except the pogo pins obviusly)

**Comment by arturo182** [comment]
Yes, soldering is required. I'm not aware of any that don't require soldering. The benefit is that you solder the FlexyPins once and then can insert and remove the modules many, many times
